name: ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - h5py
  - numpy
  - matplotlib
  - ipython
  - scikit-learn
  - pandas
  - scipy
  - seaborn
  - pydot
  - pip
  - catppuccin-jupyterlab
  - jupytext
  - ca-certificates
  - openssl
  - tensorflow
  - keras-tuner
  - tqdm
