name: ml
dependencies:
  - python=3.12
  - h5py
  - numpy
  - matplotlib
  - ipython
  - scikit-learn
  - pandas
  - scipy
  - seaborn
  - pydot
  - pip
  - catppuccin-jupyterlab

  - pip:
    - tensorflow==2.18.0
    - wget
    - graphviz
    - hyperas
    - mlxtend
    - gdown

